//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_Testapp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bid
    {
        public long bidID { get; set; }
        public long itemno { get; set; }
        public long userID { get; set; }
        public long value { get; set; }
        public string username { get; set; }
    
        public virtual item item { get; set; }
        public virtual user user { get; set; }
    }
}
