//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_Testapp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.bid = new HashSet<bid>();
            this.item = new HashSet<item>();
        }
    
        public long UserID { get; set; }
        public string Username { get; set; }
        public string Lastname { get; set; }
        public string Password { get; set; }
        public string Adress { get; set; }
        public string Firstname { get; set; }
    
        public virtual ICollection<bid> bid { get; set; }
        public virtual ICollection<item> item { get; set; }
    }
}
