//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_Testapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.bid = new HashSet<bid>();
        }
    
        public long itemno { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public System.DateTime expires { get; set; }
        public string description { get; set; }
        public long addedByID { get; set; }
    
        public virtual ICollection<bid> bid { get; set; }
        public virtual user user { get; set; }
    }
}
